### ISSUE TITLE
Animation don't starts

### ISSUE THREAD

**Issue by jakubfabijan** [goodhertz/coldtype#61]
Frame counter (and so animation) stops at frame 0. I have no idea what am I doing wrong.
![bildo](https://user-images.githubusercontent.com/53099243/130426043-9839e937-1d9d-4400-b8e8-34ef47ae1d16.png)

**Comment by stenson** [comment]
Hello! Doesn't sound like you're doing anything wrong — by default Coldtype doesn't play an animation, it just renders a single frame (by default frame 0). To play an animation, you just need to click on the viewer window (or bring it into focus some other way) and then hit the spacebar. Then you can hit the spacebar again to stop the animation.

Here's a video tutorial about using the viewer window (although it seems I don't mention the spacebar, whoops!): https://www.youtube.com/watch?v=hCGF6FZCSqc

And here are some of the main keyboard shortcuts: https://coldtype.goodhertz.com/cheatsheets/viewer.html

Hopefully that helps — let me know if it doesn't!

(Also it looks like you'll probably need to change `width=f.e()` to `wdth=f.e()` since the names of variable font axes are always four-letter codes.)

**Comment by jakubfabijan** [comment]
Work's perfect, thank you 😃
