### ISSUE TITLE
support fvar/avar userspace in variable font?

### ISSUE THREAD

**Issue by jpt** [goodhertz/coldtype#62]
hi! first of all I am loving this library so much. THANK YOU.

RE: the subject. I am trying to figure out if this is a design decision, a TODO, or something wrong with my font! couldn't find much in the docs. but it seems I can only access, for example, a `wght` axis from 0.0 to 1.0 (would expect 0-1000 for weight), and also whereas I might have an avar table with fvar (userspace) values like 100, 200, ... , 900 which is what I'd expect to be able to use. (e.g.: https://simoncozens.github.io/userspace-and-designspace/)

**Comment by jpt** [comment]
oh I can see I've misunderstood how `e` works. this is so interesting!

**Comment by jpt** [comment]
ok. I do not want access to userspace. that was quick 😆 great, simple design!

**Comment by stenson** [comment]
Thanks for trying out Coldtype! I can definitely see why this would be confusing, and it is kind of a weird choice (to automatically scale all axes from 0-1). To be honest I really only did that because I kept forgetting the min and max values some axes I was working with, and 0-1 scaling means you can plug easing equation output directly into an axis and it'll always work. _But_ I also totally realize people would want to use the actual axis values!

So there is some limited support for that (which I should really document), via the `scaleVariations` keyword that you can pass to a `StSt` (or a `Style` object). By default this is `1` (meaning do-scale), but you can set it to 0 to disable that scaling mechanism.

```python
from coldtype import *

@animation(timeline=30)
def unscaled(f):
    return (StSt("VAR", Font.Find("Barlow"), 320,
        wght=f.e("eeio", 1, rng=(22, 188)),
        wdth=f.e("eeio", 1, rng=(300, 500)),
        scaleVariations=0) # <- don't axes scale 0-1
        .align(f.a.r))
```

That said, there's a bug in the current release of Coldtype that'll throw an error if you provide a value outside of the true range (that'll be fixed in the next Coldtype release).

(Also have to admit I didn't actually know the difference between userspace & designspace — thanks for the link!)

**Comment by jpt** [comment]
Thanks for the tip on `scaleVariations`! I can see for the purpose of animation in particular, that normalizing everything between extremes at 0-1 is helpful, though. There's a lot to think about RE: how people will want to use those values, ultimately. I personally like your dead-simple solution to this even if it isn't in keeping with OT spec. have been having a blast with coldtype!

Barlow is not a good example for this as it ignores userspace entirely 😅 one day!

**Comment by jpt** [comment]
@stenson just to better illustrate this in python form in case it's helpful (and really only thinking about the weight axis here), this is pretty much the problem I was working though. I provide  a userspace value like 400 (which I know is regular weight), I get `0.3505` in return to provide to coldtype

```
def precise(number,precision=4):
	return float(f'{number:.{precision}f}')

def transformToRange(c,d,arr):
	values = []
	a = arr[0]
	b = arr[len(arr)-1]

	def affine(x,a,b,c,d):
		return (x-a)*((d-c)/(b-a))+c
		
	for x in range(0,len(arr)):
		values.append(precise(affine(arr[x],a,b,c,d)))
	return values

designspaceCoords = [18,38,62,86,104,130,152,180,212] # internal coordinates based on stem width - a pretty common type design pattern
userspaceCoords = [100,200,300,400,500,600,700,800,900] # maps to CSS values, also pretty common

def getzeroOneSpaceByUserCoord(userCoord):
    zeroOneSteps = transformToRange(0,1,designspaceCoords) 
    for i,coord in enumerate(userspaceCoords):
        if coord == userCoord:
            return zeroOneSteps[i]

print(getzeroOneSpaceByUserCoord(400))
```

of course, userspace inputs can be arbitrary, so it's a bit more complicated, but suits my use case for the moment anyway :) 

looking forward to digging more into the `rng` and `scaleVariations` example you provided. 

I really cannot stress enough how awesome coldtype is!
